export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS"
export const LOAD_POSTS_FAILURE = "LOAD_POSTS_FAILURE"

export const SET_USERS_SUCCESS = "SET_USERS_SUCCESS"
export const SET_USERS_FAILURE = "SET_USERS_FAILURE"

export const SET_CURRENT_USER = "SET_CURRENT_USER"