export const BASE_URL = 'https://jsonplaceholder.typicode.com'

export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS"
export const LOAD_POSTS_FAILURE = "LOAD_POSTS_FAILURE"

export const SET_USERS_SUCCESS = "SET_USERS_SUCCESS"
export const SET_USERS_FAILURE = "SET_USERS_FAILURE"

export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const GET_CURRENT_USER_POSTS = "GET_CURRENT_USER_POSTS"
export const SET_CURRENT_USER_POSTS = "SET_CURRENT_USER_POSTS"

export const GET_COMMENTS = "GET_COMMENTS"
export const SET_COMMENTS = "SET_COMMENTS"

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"

export const SORT_FROM_BEGIN = "SORT_FROM_BEGIN"
export const SORT_FROM_END = "SORT_FROM_END"
export const SORT_BY_DEFAULT = "SORT_BY_DEFAULT"

export const SEARCH_BY_TITLE = "SEARCH_BY_TITLE"
